// Emoji data organized by category
export const EMOJI_DATA = {
    people: [
        { e: '😀', n: 'grinning', k: ['happy', 'smile'] },
        { e: '😃', n: 'smiley', k: ['happy'] },
        { e: '😄', n: 'smile', k: ['happy', 'joy'] },
        { e: '😁', n: 'grin', k: ['happy'] },
        { e: '😆', n: 'laughing', k: ['happy', 'lol'] },
        { e: '😅', n: 'sweat smile', k: ['nervous'] },
        { e: '🤣', n: 'rofl', k: ['laugh', 'lol'] },
        { e: '😂', n: 'joy', k: ['laugh', 'tears'] },
        { e: '🙂', n: 'slight smile', k: [] },
        { e: '🙃', n: 'upside down', k: ['silly'] },
        { e: '😉', n: 'wink', k: [] },
        { e: '😊', n: 'blush', k: ['happy'] },
        { e: '😇', n: 'innocent', k: ['angel'] },
        { e: '🥰', n: 'smiling hearts', k: ['love'] },
        { e: '😍', n: 'heart eyes', k: ['love'] },
        { e: '🤩', n: 'star struck', k: ['wow'] },
        { e: '😘', n: 'kissing heart', k: ['love'] },
        { e: '😗', n: 'kissing', k: [] },
        { e: '😚', n: 'kissing closed', k: [] },
        { e: '😙', n: 'kissing smiling', k: [] },
        { e: '🥲', n: 'smile tear', k: ['sad'] },
        { e: '😋', n: 'yum', k: ['delicious'] },
        { e: '😛', n: 'tongue', k: ['playful'] },
        { e: '😜', n: 'wink tongue', k: ['playful'] },
        { e: '🤪', n: 'zany', k: ['crazy'] },
        { e: '😝', n: 'squint tongue', k: [] },
        { e: '🤑', n: 'money', k: ['rich'] },
        { e: '🤗', n: 'hugs', k: ['hug'] },
        { e: '🤭', n: 'hand over mouth', k: ['oops'] },
        { e: '🤫', n: 'shushing', k: ['quiet'] },
        { e: '🤔', n: 'thinking', k: ['hmm'] },
        { e: '🤐', n: 'zipper mouth', k: ['quiet'] },
        { e: '🤨', n: 'raised eyebrow', k: ['skeptic'] },
        { e: '😐', n: 'neutral', k: ['meh'] },
        { e: '😑', n: 'expressionless', k: [] },
        { e: '😶', n: 'no mouth', k: ['silent'] },
        { e: '😏', n: 'smirk', k: ['smug'] },
        { e: '😒', n: 'unamused', k: ['meh'] },
        { e: '🙄', n: 'roll eyes', k: ['whatever'] },
        { e: '😬', n: 'grimacing', k: ['awkward'] },
        { e: '🤥', n: 'lying', k: ['pinocchio'] },
        { e: '😌', n: 'relieved', k: ['calm'] },
        { e: '😔', n: 'pensive', k: ['sad'] },
        { e: '😪', n: 'sleepy', k: ['tired'] },
        { e: '🤤', n: 'drooling', k: ['hungry'] },
        { e: '😴', n: 'sleeping', k: ['zzz'] },
        { e: '😷', n: 'mask', k: ['sick'] },
        { e: '🤒', n: 'thermometer', k: ['sick'] },
        { e: '🤕', n: 'bandage', k: ['hurt'] },
        { e: '🤢', n: 'nauseated', k: ['sick'] },
        { e: '🤮', n: 'vomiting', k: ['sick'] },
        { e: '🤧', n: 'sneezing', k: ['sick'] },
        { e: '🥵', n: 'hot', k: ['sweating'] },
        { e: '🥶', n: 'cold', k: ['freezing'] },
        { e: '🥴', n: 'woozy', k: ['drunk'] },
        { e: '😵', n: 'dizzy', k: [] },
        { e: '🤯', n: 'exploding head', k: ['mind blown'] },
        { e: '🤠', n: 'cowboy', k: [] },
        { e: '🥳', n: 'party', k: ['celebrate'] },
        { e: '🥸', n: 'disguise', k: [] },
        { e: '😎', n: 'sunglasses', k: ['cool'] },
        { e: '🤓', n: 'nerd', k: ['geek'] },
        { e: '🧐', n: 'monocle', k: ['curious'] },
        { e: '😕', n: 'confused', k: [] },
        { e: '😟', n: 'worried', k: [] },
        { e: '🙁', n: 'frown', k: ['sad'] },
        { e: '😮', n: 'open mouth', k: ['surprised'] },
        { e: '😯', n: 'hushed', k: [] },
        { e: '😲', n: 'astonished', k: ['shocked'] },
        { e: '😳', n: 'flushed', k: ['embarrassed'] },
        { e: '🥺', n: 'pleading', k: ['puppy eyes'] },
        { e: '😦', n: 'frowning', k: [] },
        { e: '😧', n: 'anguished', k: [] },
        { e: '😨', n: 'fearful', k: ['scared'] },
        { e: '😰', n: 'anxious', k: ['nervous'] },
        { e: '😥', n: 'sad relieved', k: [] },
        { e: '😢', n: 'cry', k: ['sad', 'tear'] },
        { e: '😭', n: 'sob', k: ['crying'] },
        { e: '😱', n: 'scream', k: ['scared'] },
        { e: '😖', n: 'confounded', k: [] },
        { e: '😣', n: 'persevere', k: [] },
        { e: '😞', n: 'disappointed', k: ['sad'] },
        { e: '😓', n: 'downcast', k: [] },
        { e: '😩', n: 'weary', k: ['tired'] },
        { e: '😫', n: 'tired', k: [] },
        { e: '🥱', n: 'yawning', k: ['sleepy'] },
        { e: '😤', n: 'triumph', k: ['angry'] },
        { e: '😡', n: 'rage', k: ['angry'] },
        { e: '😠', n: 'angry', k: ['mad'] },
        { e: '🤬', n: 'cursing', k: ['angry'] },
        { e: '😈', n: 'imp', k: ['devil'] },
        { e: '👿', n: 'angry imp', k: ['devil'] },
        { e: '💀', n: 'skull', k: ['dead'] },
        { e: '☠️', n: 'crossbones', k: ['danger'] },
        { e: '💩', n: 'poop', k: [] },
        { e: '🤡', n: 'clown', k: [] },
        { e: '👹', n: 'ogre', k: ['monster'] },
        { e: '👺', n: 'goblin', k: ['monster'] },
        { e: '👻', n: 'ghost', k: ['halloween'] },
        { e: '👽', n: 'alien', k: ['ufo'] },
        { e: '👾', n: 'space invader', k: ['game'] },
        { e: '🤖', n: 'robot', k: ['bot'] },
        { e: '👋', n: 'wave', k: ['hello', 'bye'] },
        { e: '🤚', n: 'raised back', k: [] },
        { e: '🖐️', n: 'hand splayed', k: [] },
        { e: '✋', n: 'raised hand', k: ['stop'] },
        { e: '🖖', n: 'vulcan', k: ['spock'] },
        { e: '👌', n: 'ok', k: ['perfect'] },
        { e: '🤌', n: 'pinched', k: ['italian'] },
        { e: '🤏', n: 'pinching', k: ['small'] },
        { e: '✌️', n: 'victory', k: ['peace'] },
        { e: '🤞', n: 'crossed fingers', k: ['luck'] },
        { e: '🤟', n: 'love you', k: [] },
        { e: '🤘', n: 'rock', k: ['metal'] },
        { e: '🤙', n: 'call me', k: ['shaka'] },
        { e: '👈', n: 'left', k: ['point'] },
        { e: '👉', n: 'right', k: ['point'] },
        { e: '👆', n: 'up', k: ['point'] },
        { e: '👇', n: 'down', k: ['point'] },
        { e: '☝️', n: 'index up', k: ['point'] },
        { e: '👍', n: 'thumbs up', k: ['like', 'yes'] },
        { e: '👎', n: 'thumbs down', k: ['dislike', 'no'] },
        { e: '✊', n: 'fist', k: ['punch'] },
        { e: '👊', n: 'punch', k: ['fist bump'] },
        { e: '🤛', n: 'left fist', k: [] },
        { e: '🤜', n: 'right fist', k: [] },
        { e: '👏', n: 'clap', k: ['applause'] },
        { e: '🙌', n: 'raised hands', k: ['hooray'] },
        { e: '👐', n: 'open hands', k: [] },
        { e: '🤲', n: 'palms up', k: [] },
        { e: '🤝', n: 'handshake', k: ['deal'] },
        { e: '🙏', n: 'pray', k: ['thanks', 'please'] },
    ],
    nature: [
        { e: '🐶', n: 'dog', k: ['puppy'] },
        { e: '🐱', n: 'cat', k: ['kitten'] },
        { e: '🐭', n: 'mouse', k: [] },
        { e: '🐹', n: 'hamster', k: [] },
        { e: '🐰', n: 'rabbit', k: ['bunny'] },
        { e: '🦊', n: 'fox', k: [] },
        { e: '🐻', n: 'bear', k: [] },
        { e: '🐼', n: 'panda', k: [] },
        { e: '🐨', n: 'koala', k: [] },
        { e: '🐯', n: 'tiger', k: [] },
        { e: '🦁', n: 'lion', k: [] },
        { e: '🐮', n: 'cow', k: [] },
        { e: '🐷', n: 'pig', k: [] },
        { e: '🐸', n: 'frog', k: [] },
        { e: '🐵', n: 'monkey', k: [] },
        { e: '🐔', n: 'chicken', k: [] },
        { e: '🐧', n: 'penguin', k: [] },
        { e: '🐦', n: 'bird', k: [] },
        { e: '🐤', n: 'chick', k: [] },
        { e: '🦆', n: 'duck', k: [] },
        { e: '🦅', n: 'eagle', k: [] },
        { e: '🦉', n: 'owl', k: [] },
        { e: '🦇', n: 'bat', k: [] },
        { e: '🐺', n: 'wolf', k: [] },
        { e: '🐗', n: 'boar', k: [] },
        { e: '🐴', n: 'horse', k: [] },
        { e: '🦄', n: 'unicorn', k: ['magic'] },
        { e: '🐝', n: 'bee', k: ['honey'] },
        { e: '🐛', n: 'bug', k: [] },
        { e: '🦋', n: 'butterfly', k: [] },
        { e: '🐌', n: 'snail', k: [] },
        { e: '🐞', n: 'ladybug', k: [] },
        { e: '🐜', n: 'ant', k: [] },
        { e: '🦟', n: 'mosquito', k: [] },
        { e: '🐢', n: 'turtle', k: [] },
        { e: '🐍', n: 'snake', k: [] },
        { e: '🦎', n: 'lizard', k: [] },
        { e: '🦂', n: 'scorpion', k: [] },
        { e: '🦀', n: 'crab', k: [] },
        { e: '🦞', n: 'lobster', k: [] },
        { e: '🦐', n: 'shrimp', k: [] },
        { e: '🦑', n: 'squid', k: [] },
        { e: '🐙', n: 'octopus', k: [] },
        { e: '🐠', n: 'fish', k: [] },
        { e: '🐟', n: 'fish', k: [] },
        { e: '🐡', n: 'blowfish', k: [] },
        { e: '🐬', n: 'dolphin', k: [] },
        { e: '🦈', n: 'shark', k: [] },
        { e: '🐳', n: 'whale', k: [] },
        { e: '🐋', n: 'whale', k: [] },
        { e: '🌸', n: 'cherry blossom', k: ['flower'] },
        { e: '💮', n: 'flower', k: [] },
        { e: '🏵️', n: 'rosette', k: [] },
        { e: '🌹', n: 'rose', k: ['flower'] },
        { e: '🥀', n: 'wilted', k: ['dead'] },
        { e: '🌺', n: 'hibiscus', k: ['flower'] },
        { e: '🌻', n: 'sunflower', k: [] },
        { e: '🌼', n: 'blossom', k: ['flower'] },
        { e: '🌷', n: 'tulip', k: ['flower'] },
        { e: '🌱', n: 'seedling', k: ['plant'] },
        { e: '🌲', n: 'evergreen', k: ['tree'] },
        { e: '🌳', n: 'tree', k: [] },
        { e: '🌴', n: 'palm', k: ['tree'] },
        { e: '🌵', n: 'cactus', k: [] },
        { e: '🌾', n: 'rice', k: [] },
        { e: '🌿', n: 'herb', k: ['plant'] },
        { e: '☘️', n: 'shamrock', k: ['clover'] },
        { e: '🍀', n: 'four leaf', k: ['luck'] },
        { e: '🍁', n: 'maple leaf', k: ['fall'] },
        { e: '🍂', n: 'fallen leaf', k: ['autumn'] },
        { e: '🍃', n: 'leaves', k: ['wind'] },
        { e: '🌍', n: 'earth', k: ['world'] },
        { e: '🌎', n: 'earth americas', k: ['world'] },
        { e: '🌏', n: 'earth asia', k: ['world'] },
        { e: '🌑', n: 'new moon', k: [] },
        { e: '🌕', n: 'full moon', k: [] },
        { e: '🌙', n: 'crescent moon', k: ['night'] },
        { e: '⭐', n: 'star', k: [] },
        { e: '🌟', n: 'glowing star', k: [] },
        { e: '✨', n: 'sparkles', k: ['magic'] },
        { e: '⚡', n: 'lightning', k: ['electric'] },
        { e: '🔥', n: 'fire', k: ['hot', 'lit'] },
        { e: '💧', n: 'droplet', k: ['water'] },
        { e: '🌊', n: 'wave', k: ['ocean'] },
        { e: '☀️', n: 'sun', k: ['sunny'] },
        { e: '🌤️', n: 'sun clouds', k: [] },
        { e: '⛅', n: 'cloudy', k: [] },
        { e: '🌧️', n: 'rain', k: [] },
        { e: '⛈️', n: 'storm', k: ['thunder'] },
        { e: '🌩️', n: 'lightning cloud', k: [] },
        { e: '❄️', n: 'snowflake', k: ['cold', 'winter'] },
        { e: '☃️', n: 'snowman', k: ['winter'] },
        { e: '🌈', n: 'rainbow', k: [] },
    ],
    food: [
        { e: '🍎', n: 'apple', k: ['fruit'] },
        { e: '🍊', n: 'orange', k: ['fruit'] },
        { e: '🍋', n: 'lemon', k: ['fruit'] },
        { e: '🍌', n: 'banana', k: ['fruit'] },
        { e: '🍉', n: 'watermelon', k: ['fruit'] },
        { e: '🍇', n: 'grapes', k: ['fruit'] },
        { e: '🍓', n: 'strawberry', k: ['fruit'] },
        { e: '🫐', n: 'blueberries', k: ['fruit'] },
        { e: '🍒', n: 'cherries', k: ['fruit'] },
        { e: '🍑', n: 'peach', k: ['fruit'] },
        { e: '🥭', n: 'mango', k: ['fruit'] },
        { e: '🍍', n: 'pineapple', k: ['fruit'] },
        { e: '🥥', n: 'coconut', k: [] },
        { e: '🥝', n: 'kiwi', k: ['fruit'] },
        { e: '🍅', n: 'tomato', k: [] },
        { e: '🥑', n: 'avocado', k: [] },
        { e: '🥦', n: 'broccoli', k: ['vegetable'] },
        { e: '🥬', n: 'lettuce', k: ['vegetable'] },
        { e: '🥒', n: 'cucumber', k: ['vegetable'] },
        { e: '🌶️', n: 'pepper', k: ['hot', 'spicy'] },
        { e: '🌽', n: 'corn', k: [] },
        { e: '🥕', n: 'carrot', k: ['vegetable'] },
        { e: '🧄', n: 'garlic', k: [] },
        { e: '🧅', n: 'onion', k: [] },
        { e: '🥔', n: 'potato', k: [] },
        { e: '🍞', n: 'bread', k: [] },
        { e: '🥐', n: 'croissant', k: [] },
        { e: '🥖', n: 'baguette', k: ['bread'] },
        { e: '🥨', n: 'pretzel', k: [] },
        { e: '🧀', n: 'cheese', k: [] },
        { e: '🥚', n: 'egg', k: [] },
        { e: '🍳', n: 'cooking', k: ['egg', 'breakfast'] },
        { e: '🥞', n: 'pancakes', k: ['breakfast'] },
        { e: '🧇', n: 'waffle', k: ['breakfast'] },
        { e: '🥓', n: 'bacon', k: [] },
        { e: '🥩', n: 'steak', k: ['meat'] },
        { e: '🍗', n: 'chicken leg', k: [] },
        { e: '🍖', n: 'meat bone', k: [] },
        { e: '🌭', n: 'hotdog', k: [] },
        { e: '🍔', n: 'burger', k: ['hamburger'] },
        { e: '🍟', n: 'fries', k: ['french fries'] },
        { e: '🍕', n: 'pizza', k: [] },
        { e: '🥪', n: 'sandwich', k: [] },
        { e: '🥙', n: 'pita', k: [] },
        { e: '🧆', n: 'falafel', k: [] },
        { e: '🌮', n: 'taco', k: [] },
        { e: '🌯', n: 'burrito', k: [] },
        { e: '🥗', n: 'salad', k: [] },
        { e: '🍝', n: 'spaghetti', k: ['pasta'] },
        { e: '🍜', n: 'noodles', k: ['ramen'] },
        { e: '🍲', n: 'stew', k: ['soup'] },
        { e: '🍛', n: 'curry', k: [] },
        { e: '🍣', n: 'sushi', k: [] },
        { e: '🍱', n: 'bento', k: [] },
        { e: '🥟', n: 'dumpling', k: [] },
        { e: '🦪', n: 'oyster', k: [] },
        { e: '🍤', n: 'shrimp', k: [] },
        { e: '🍙', n: 'rice ball', k: [] },
        { e: '🍚', n: 'rice', k: [] },
        { e: '🍘', n: 'rice cracker', k: [] },
        { e: '🍧', n: 'shaved ice', k: [] },
        { e: '🍨', n: 'ice cream', k: [] },
        { e: '🍦', n: 'soft serve', k: [] },
        { e: '🥧', n: 'pie', k: [] },
        { e: '🧁', n: 'cupcake', k: [] },
        { e: '🍰', n: 'cake', k: [] },
        { e: '🎂', n: 'birthday cake', k: ['party'] },
        { e: '🍮', n: 'custard', k: [] },
        { e: '🍭', n: 'lollipop', k: ['candy'] },
        { e: '🍬', n: 'candy', k: [] },
        { e: '🍫', n: 'chocolate', k: [] },
        { e: '🍿', n: 'popcorn', k: [] },
        { e: '🍩', n: 'doughnut', k: [] },
        { e: '🍪', n: 'cookie', k: [] },
        { e: '☕', n: 'coffee', k: ['hot'] },
        { e: '🍵', n: 'tea', k: [] },
        { e: '🧃', n: 'juice box', k: [] },
        { e: '🥤', n: 'cup straw', k: ['soda'] },
        { e: '🧋', n: 'bubble tea', k: ['boba'] },
        { e: '🍶', n: 'sake', k: [] },
        { e: '🍺', n: 'beer', k: [] },
        { e: '🍻', n: 'beers', k: ['cheers'] },
        { e: '🥂', n: 'champagne', k: ['cheers'] },
        { e: '🍷', n: 'wine', k: [] },
        { e: '🥃', n: 'whiskey', k: [] },
        { e: '🍸', n: 'cocktail', k: [] },
        { e: '🍹', n: 'tropical drink', k: [] },
    ],
    activities: [
        { e: '⚽', n: 'soccer', k: ['football'] },
        { e: '🏀', n: 'basketball', k: [] },
        { e: '🏈', n: 'football', k: ['american'] },
        { e: '⚾', n: 'baseball', k: [] },
        { e: '🥎', n: 'softball', k: [] },
        { e: '🎾', n: 'tennis', k: [] },
        { e: '🏐', n: 'volleyball', k: [] },
        { e: '🏉', n: 'rugby', k: [] },
        { e: '🥏', n: 'frisbee', k: [] },
        { e: '🎱', n: 'pool', k: ['billiards'] },
        { e: '🏓', n: 'ping pong', k: [] },
        { e: '🏸', n: 'badminton', k: [] },
        { e: '🏒', n: 'hockey', k: [] },
        { e: '🏑', n: 'field hockey', k: [] },
        { e: '🥍', n: 'lacrosse', k: [] },
        { e: '🏏', n: 'cricket', k: [] },
        { e: '🥅', n: 'goal', k: [] },
        { e: '⛳', n: 'golf', k: [] },
        { e: '🏹', n: 'bow arrow', k: ['archery'] },
        { e: '🎣', n: 'fishing', k: [] },
        { e: '🤿', n: 'diving mask', k: [] },
        { e: '🥊', n: 'boxing', k: [] },
        { e: '🥋', n: 'martial arts', k: [] },
        { e: '🎿', n: 'skiing', k: [] },
        { e: '⛷️', n: 'skier', k: [] },
        { e: '🏂', n: 'snowboard', k: [] },
        { e: '🛷', n: 'sled', k: [] },
        { e: '⛸️', n: 'ice skate', k: [] },
        { e: '🎯', n: 'bullseye', k: ['target', 'dart'] },
        { e: '🪀', n: 'yo-yo', k: [] },
        { e: '🪁', n: 'kite', k: [] },
        { e: '🎮', n: 'video game', k: ['gaming'] },
        { e: '🕹️', n: 'joystick', k: ['gaming'] },
        { e: '🎲', n: 'dice', k: ['game'] },
        { e: '🧩', n: 'puzzle', k: [] },
        { e: '♟️', n: 'chess', k: [] },
        { e: '🎭', n: 'theater', k: ['drama'] },
        { e: '🎨', n: 'art', k: ['palette', 'paint'] },
        { e: '🎬', n: 'clapper', k: ['movie', 'film'] },
        { e: '🎤', n: 'microphone', k: ['sing', 'karaoke'] },
        { e: '🎧', n: 'headphones', k: ['music'] },
        { e: '🎼', n: 'music', k: ['score'] },
        { e: '🎹', n: 'piano', k: ['keyboard'] },
        { e: '🥁', n: 'drum', k: [] },
        { e: '🪘', n: 'drum', k: [] },
        { e: '🎷', n: 'saxophone', k: [] },
        { e: '🎺', n: 'trumpet', k: [] },
        { e: '🎸', n: 'guitar', k: [] },
        { e: '🪕', n: 'banjo', k: [] },
        { e: '🎻', n: 'violin', k: [] },
        { e: '🏆', n: 'trophy', k: ['winner'] },
        { e: '🥇', n: 'gold medal', k: ['first'] },
        { e: '🥈', n: 'silver medal', k: ['second'] },
        { e: '🥉', n: 'bronze medal', k: ['third'] },
        { e: '🎖️', n: 'medal', k: [] },
        { e: '🎗️', n: 'ribbon', k: [] },
        { e: '🎪', n: 'circus', k: [] },
        { e: '🎠', n: 'carousel', k: [] },
        { e: '🎡', n: 'ferris wheel', k: [] },
        { e: '🎢', n: 'roller coaster', k: [] },
    ],
    travel: [
        { e: '🚗', n: 'car', k: ['automobile'] },
        { e: '🚕', n: 'taxi', k: [] },
        { e: '🚙', n: 'suv', k: ['car'] },
        { e: '🚌', n: 'bus', k: [] },
        { e: '🚎', n: 'trolleybus', k: [] },
        { e: '🏎️', n: 'racing car', k: [] },
        { e: '🚓', n: 'police car', k: [] },
        { e: '🚑', n: 'ambulance', k: [] },
        { e: '🚒', n: 'fire truck', k: [] },
        { e: '🚐', n: 'minibus', k: [] },
        { e: '🛻', n: 'pickup', k: ['truck'] },
        { e: '🚚', n: 'truck', k: [] },
        { e: '🚛', n: 'semi', k: ['truck'] },
        { e: '🚜', n: 'tractor', k: [] },
        { e: '🏍️', n: 'motorcycle', k: [] },
        { e: '🛵', n: 'scooter', k: [] },
        { e: '🚲', n: 'bicycle', k: ['bike'] },
        { e: '🛴', n: 'kick scooter', k: [] },
        { e: '🚂', n: 'locomotive', k: ['train'] },
        { e: '🚃', n: 'railway car', k: ['train'] },
        { e: '🚄', n: 'bullet train', k: [] },
        { e: '🚅', n: 'train', k: [] },
        { e: '🚆', n: 'train', k: [] },
        { e: '🚇', n: 'metro', k: ['subway'] },
        { e: '🚈', n: 'light rail', k: [] },
        { e: '🚉', n: 'station', k: [] },
        { e: '✈️', n: 'airplane', k: ['plane'] },
        { e: '🛩️', n: 'small plane', k: [] },
        { e: '🛫', n: 'departure', k: ['takeoff'] },
        { e: '🛬', n: 'arrival', k: ['landing'] },
        { e: '🚀', n: 'rocket', k: ['space'] },
        { e: '🛸', n: 'ufo', k: ['alien'] },
        { e: '🚁', n: 'helicopter', k: [] },
        { e: '🛶', n: 'canoe', k: [] },
        { e: '⛵', n: 'sailboat', k: [] },
        { e: '🚤', n: 'speedboat', k: [] },
        { e: '🛥️', n: 'motorboat', k: [] },
        { e: '🛳️', n: 'cruise', k: ['ship'] },
        { e: '⛴️', n: 'ferry', k: [] },
        { e: '🚢', n: 'ship', k: [] },
        { e: '⚓', n: 'anchor', k: ['nautical'] },
        { e: '🗺️', n: 'map', k: ['world'] },
        { e: '🧭', n: 'compass', k: [] },
        { e: '🏔️', n: 'mountain', k: [] },
        { e: '⛰️', n: 'mountain', k: [] },
        { e: '🌋', n: 'volcano', k: [] },
        { e: '🗻', n: 'mount fuji', k: [] },
        { e: '🏕️', n: 'camping', k: ['tent'] },
        { e: '🏖️', n: 'beach', k: [] },
        { e: '🏜️', n: 'desert', k: [] },
        { e: '🏝️', n: 'island', k: [] },
        { e: '🏞️', n: 'national park', k: [] },
        { e: '🏟️', n: 'stadium', k: [] },
        { e: '🏛️', n: 'classical building', k: [] },
        { e: '🏗️', n: 'construction', k: [] },
        { e: '🧱', n: 'brick', k: [] },
        { e: '🏠', n: 'house', k: ['home'] },
        { e: '🏡', n: 'house garden', k: ['home'] },
        { e: '🏢', n: 'office', k: ['building'] },
        { e: '🏬', n: 'department store', k: [] },
        { e: '🏣', n: 'post office', k: [] },
        { e: '🏥', n: 'hospital', k: [] },
        { e: '🏦', n: 'bank', k: [] },
        { e: '🏨', n: 'hotel', k: [] },
        { e: '🏩', n: 'love hotel', k: [] },
        { e: '🏪', n: 'convenience store', k: [] },
        { e: '🏫', n: 'school', k: [] },
        { e: '💒', n: 'wedding', k: ['church'] },
        { e: '⛪', n: 'church', k: [] },
        { e: '🕌', n: 'mosque', k: [] },
        { e: '🕍', n: 'synagogue', k: [] },
        { e: '⛩️', n: 'shinto shrine', k: [] },
        { e: '🕋', n: 'kaaba', k: [] },
        { e: '⛲', n: 'fountain', k: [] },
        { e: '⛺', n: 'tent', k: ['camping'] },
        { e: '🌃', n: 'night stars', k: ['city'] },
        { e: '🌆', n: 'cityscape', k: ['sunset'] },
        { e: '🌇', n: 'sunset', k: [] },
        { e: '🌉', n: 'bridge night', k: [] },
        { e: '🗼', n: 'tokyo tower', k: [] },
        { e: '🗽', n: 'statue liberty', k: [] },
        { e: '🗿', n: 'moai', k: ['easter island'] },
    ],
    objects: [
        { e: '⌚', n: 'watch', k: ['time'] },
        { e: '📱', n: 'phone', k: ['mobile', 'iphone'] },
        { e: '📲', n: 'mobile arrow', k: ['call'] },
        { e: '💻', n: 'laptop', k: ['computer'] },
        { e: '⌨️', n: 'keyboard', k: [] },
        { e: '🖥️', n: 'desktop', k: ['computer'] },
        { e: '🖨️', n: 'printer', k: [] },
        { e: '🖱️', n: 'mouse', k: ['computer'] },
        { e: '💽', n: 'disk', k: ['computer'] },
        { e: '💾', n: 'floppy', k: ['save'] },
        { e: '💿', n: 'cd', k: ['disc'] },
        { e: '📀', n: 'dvd', k: [] },
        { e: '📷', n: 'camera', k: ['photo'] },
        { e: '📸', n: 'camera flash', k: ['photo'] },
        { e: '📹', n: 'video camera', k: [] },
        { e: '🎥', n: 'movie camera', k: ['film'] },
        { e: '📽️', n: 'projector', k: [] },
        { e: '📺', n: 'tv', k: ['television'] },
        { e: '📻', n: 'radio', k: [] },
        { e: '🎙️', n: 'studio mic', k: ['podcast'] },
        { e: '📡', n: 'satellite', k: [] },
        { e: '🔋', n: 'battery', k: [] },
        { e: '🔌', n: 'plug', k: ['electric'] },
        { e: '💡', n: 'lightbulb', k: ['idea'] },
        { e: '🔦', n: 'flashlight', k: [] },
        { e: '🕯️', n: 'candle', k: [] },
        { e: '📚', n: 'books', k: ['library'] },
        { e: '📖', n: 'open book', k: ['read'] },
        { e: '📝', n: 'memo', k: ['note', 'write'] },
        { e: '📓', n: 'notebook', k: [] },
        { e: '📒', n: 'ledger', k: [] },
        { e: '📃', n: 'page curl', k: ['document'] },
        { e: '📄', n: 'page', k: ['document'] },
        { e: '📰', n: 'newspaper', k: ['news'] },
        { e: '🗞️', n: 'rolled newspaper', k: [] },
        { e: '📑', n: 'bookmark tabs', k: [] },
        { e: '🔖', n: 'bookmark', k: [] },
        { e: '🏷️', n: 'label', k: ['tag'] },
        { e: '💰', n: 'money bag', k: ['rich'] },
        { e: '💵', n: 'dollar', k: ['money'] },
        { e: '💳', n: 'credit card', k: ['payment'] },
        { e: '✉️', n: 'envelope', k: ['email', 'mail'] },
        { e: '📧', n: 'email', k: ['mail'] },
        { e: '📨', n: 'incoming envelope', k: [] },
        { e: '📩', n: 'envelope arrow', k: [] },
        { e: '📦', n: 'package', k: ['box'] },
        { e: '📫', n: 'mailbox', k: [] },
        { e: '📪', n: 'mailbox lowered', k: [] },
        { e: '📬', n: 'mailbox raised', k: [] },
        { e: '📮', n: 'postbox', k: [] },
        { e: '🗳️', n: 'ballot box', k: ['vote'] },
        { e: '✏️', n: 'pencil', k: ['write'] },
        { e: '✒️', n: 'pen', k: [] },
        { e: '🖊️', n: 'pen', k: [] },
        { e: '🖋️', n: 'fountain pen', k: [] },
        { e: '🖍️', n: 'crayon', k: [] },
        { e: '📐', n: 'triangular ruler', k: [] },
        { e: '📏', n: 'ruler', k: [] },
        { e: '📁', n: 'folder', k: [] },
        { e: '📂', n: 'open folder', k: [] },
        { e: '🗂️', n: 'dividers', k: ['tabs'] },
        { e: '📅', n: 'calendar', k: ['date'] },
        { e: '📆', n: 'tear off calendar', k: [] },
        { e: '🗓️', n: 'spiral calendar', k: [] },
        { e: '📇', n: 'card index', k: [] },
        { e: '📈', n: 'chart up', k: ['growth'] },
        { e: '📉', n: 'chart down', k: ['decline'] },
        { e: '📊', n: 'bar chart', k: ['stats'] },
        { e: '📋', n: 'clipboard', k: [] },
        { e: '📌', n: 'pushpin', k: ['pin'] },
        { e: '📍', n: 'pin', k: ['location'] },
        { e: '📎', n: 'paperclip', k: [] },
        { e: '🔗', n: 'link', k: ['chain'] },
        { e: '🔒', n: 'locked', k: ['security'] },
        { e: '🔓', n: 'unlocked', k: [] },
        { e: '🔐', n: 'locked key', k: [] },
        { e: '🔑', n: 'key', k: [] },
        { e: '🗝️', n: 'old key', k: [] },
        { e: '🔨', n: 'hammer', k: ['tool'] },
        { e: '🪓', n: 'axe', k: [] },
        { e: '⛏️', n: 'pick', k: [] },
        { e: '🔧', n: 'wrench', k: ['tool'] },
        { e: '🔩', n: 'nut bolt', k: [] },
        { e: '⚙️', n: 'gear', k: ['settings'] },
        { e: '🧲', n: 'magnet', k: [] },
        { e: '🔬', n: 'microscope', k: ['science'] },
        { e: '🔭', n: 'telescope', k: [] },
        { e: '💊', n: 'pill', k: ['medicine'] },
        { e: '💉', n: 'syringe', k: ['vaccine'] },
        { e: '🩹', n: 'bandage', k: [] },
        { e: '🧬', n: 'dna', k: ['science'] },
    ],
    symbols: [
        { e: '❤️', n: 'red heart', k: ['love'] },
        { e: '🧡', n: 'orange heart', k: ['love'] },
        { e: '💛', n: 'yellow heart', k: ['love'] },
        { e: '💚', n: 'green heart', k: ['love'] },
        { e: '💙', n: 'blue heart', k: ['love'] },
        { e: '💜', n: 'purple heart', k: ['love'] },
        { e: '🖤', n: 'black heart', k: ['love'] },
        { e: '🤍', n: 'white heart', k: ['love'] },
        { e: '🤎', n: 'brown heart', k: ['love'] },
        { e: '💔', n: 'broken heart', k: ['sad'] },
        { e: '❣️', n: 'heart exclamation', k: [] },
        { e: '💕', n: 'two hearts', k: ['love'] },
        { e: '💞', n: 'revolving hearts', k: [] },
        { e: '💓', n: 'beating heart', k: [] },
        { e: '💗', n: 'growing heart', k: [] },
        { e: '💖', n: 'sparkling heart', k: [] },
        { e: '💘', n: 'heart arrow', k: ['cupid'] },
        { e: '💝', n: 'heart ribbon', k: ['gift'] },
        { e: '💟', n: 'heart decoration', k: [] },
        { e: '☮️', n: 'peace', k: [] },
        { e: '✝️', n: 'cross', k: ['christian'] },
        { e: '☪️', n: 'star crescent', k: ['islam'] },
        { e: '🕉️', n: 'om', k: ['hindu'] },
        { e: '☯️', n: 'yin yang', k: ['balance'] },
        { e: '✡️', n: 'star david', k: ['jewish'] },
        { e: '♈', n: 'aries', k: ['zodiac'] },
        { e: '♉', n: 'taurus', k: ['zodiac'] },
        { e: '♊', n: 'gemini', k: ['zodiac'] },
        { e: '♋', n: 'cancer', k: ['zodiac'] },
        { e: '♌', n: 'leo', k: ['zodiac'] },
        { e: '♍', n: 'virgo', k: ['zodiac'] },
        { e: '♎', n: 'libra', k: ['zodiac'] },
        { e: '♏', n: 'scorpio', k: ['zodiac'] },
        { e: '♐', n: 'sagittarius', k: ['zodiac'] },
        { e: '♑', n: 'capricorn', k: ['zodiac'] },
        { e: '♒', n: 'aquarius', k: ['zodiac'] },
        { e: '♓', n: 'pisces', k: ['zodiac'] },
        { e: '🆔', n: 'id', k: ['identity'] },
        { e: '⚛️', n: 'atom', k: ['science'] },
        { e: '🈳', n: 'vacancy', k: [] },
        { e: '🈺', n: 'open', k: [] },
        { e: '🈸', n: 'application', k: [] },
        { e: '🉐', n: 'bargain', k: [] },
        { e: '✅', n: 'check', k: ['done', 'yes'] },
        { e: '❌', n: 'x', k: ['no', 'wrong'] },
        { e: '❎', n: 'x mark', k: ['no'] },
        { e: '➕', n: 'plus', k: ['add'] },
        { e: '➖', n: 'minus', k: ['subtract'] },
        { e: '➗', n: 'divide', k: [] },
        { e: '➰', n: 'loop', k: [] },
        { e: '➿', n: 'double loop', k: [] },
        { e: '〽️', n: 'part alternation', k: [] },
        { e: '✳️', n: 'eight spoked', k: ['asterisk'] },
        { e: '✴️', n: 'eight pointed', k: ['star'] },
        { e: '❇️', n: 'sparkle', k: [] },
        { e: '‼️', n: 'double exclamation', k: [] },
        { e: '⁉️', n: 'exclamation question', k: [] },
        { e: '❓', n: 'question', k: [] },
        { e: '❔', n: 'white question', k: [] },
        { e: '❕', n: 'white exclamation', k: [] },
        { e: '❗', n: 'exclamation', k: ['alert'] },
        { e: '〰️', n: 'wavy dash', k: [] },
        { e: '©️', n: 'copyright', k: [] },
        { e: '®️', n: 'registered', k: [] },
        { e: '™️', n: 'trademark', k: [] },
        { e: '🔴', n: 'red circle', k: [] },
        { e: '🟠', n: 'orange circle', k: [] },
        { e: '🟡', n: 'yellow circle', k: [] },
        { e: '🟢', n: 'green circle', k: [] },
        { e: '🔵', n: 'blue circle', k: [] },
        { e: '🟣', n: 'purple circle', k: [] },
        { e: '🟤', n: 'brown circle', k: [] },
        { e: '⚫', n: 'black circle', k: [] },
        { e: '⚪', n: 'white circle', k: [] },
        { e: '🔺', n: 'red triangle up', k: [] },
        { e: '🔻', n: 'red triangle down', k: [] },
        { e: '🔸', n: 'orange diamond', k: [] },
        { e: '🔹', n: 'blue diamond', k: [] },
        { e: '🔶', n: 'large orange diamond', k: [] },
        { e: '🔷', n: 'large blue diamond', k: [] },
        { e: '▪️', n: 'black square', k: [] },
        { e: '▫️', n: 'white square', k: [] },
        { e: '◾', n: 'black medium square', k: [] },
        { e: '◽', n: 'white medium square', k: [] },
        { e: '🟥', n: 'red square', k: [] },
        { e: '🟧', n: 'orange square', k: [] },
        { e: '🟨', n: 'yellow square', k: [] },
        { e: '🟩', n: 'green square', k: [] },
        { e: '🟦', n: 'blue square', k: [] },
        { e: '🟪', n: 'purple square', k: [] },
    ],
    flags: [
        { e: '🏁', n: 'checkered flag', k: ['race', 'finish'] },
        { e: '🚩', n: 'triangular flag', k: [] },
        { e: '🎌', n: 'crossed flags', k: [] },
        { e: '🏴', n: 'black flag', k: [] },
        { e: '🏳️', n: 'white flag', k: ['surrender'] },
        { e: '🏳️‍🌈', n: 'rainbow flag', k: ['pride', 'lgbtq'] },
        { e: '🏴‍☠️', n: 'pirate flag', k: [] },
        { e: '🇺🇸', n: 'usa', k: ['america', 'united states'] },
        { e: '🇬🇧', n: 'uk', k: ['britain', 'england'] },
        { e: '🇫🇷', n: 'france', k: [] },
        { e: '🇩🇪', n: 'germany', k: [] },
        { e: '🇮🇹', n: 'italy', k: [] },
        { e: '🇪🇸', n: 'spain', k: [] },
        { e: '🇵🇹', n: 'portugal', k: [] },
        { e: '🇳🇱', n: 'netherlands', k: [] },
        { e: '🇧🇪', n: 'belgium', k: [] },
        { e: '🇨🇭', n: 'switzerland', k: [] },
        { e: '🇦🇹', n: 'austria', k: [] },
        { e: '🇵🇱', n: 'poland', k: [] },
        { e: '🇷🇺', n: 'russia', k: [] },
        { e: '🇺🇦', n: 'ukraine', k: [] },
        { e: '🇨🇳', n: 'china', k: [] },
        { e: '🇯🇵', n: 'japan', k: [] },
        { e: '🇰🇷', n: 'korea', k: ['south korea'] },
        { e: '🇮🇳', n: 'india', k: [] },
        { e: '🇧🇷', n: 'brazil', k: [] },
        { e: '🇲🇽', n: 'mexico', k: [] },
        { e: '🇨🇦', n: 'canada', k: [] },
        { e: '🇦🇺', n: 'australia', k: [] },
        { e: '🇳🇿', n: 'new zealand', k: [] },
    ],
};

// Get all emojis in flat array for search
export const getAllEmojis = () => {
    const all = [];
    for (const [category, emojis] of Object.entries(EMOJI_DATA)) {
        emojis.forEach(item => {
            all.push({ ...item, category });
        });
    }
    return all;
};
