// Lucide icon list for the Icons tab
export const ICON_LIST = [
    { name: 'hash', keywords: ['number', '123'] },
    { name: 'accessibility', keywords: ['a11y', 'disabled'] },
    { name: 'activity', keywords: ['pulse', 'health'] },
    { name: 'airplay', keywords: ['stream'] },
    { name: 'alarm-clock', keywords: ['time', 'alert'] },
    { name: 'album', keywords: ['music', 'photo'] },
    { name: 'alert-circle', keywords: ['warning'] },
    { name: 'alert-triangle', keywords: ['warning', 'danger'] },
    { name: 'anchor', keywords: ['nautical', 'ship'] },
    { name: 'aperture', keywords: ['camera', 'photo'] },
    { name: 'archive', keywords: ['box', 'storage'] },
    { name: 'arrow-down', keywords: ['download'] },
    { name: 'arrow-left', keywords: ['back'] },
    { name: 'arrow-right', keywords: ['forward', 'next'] },
    { name: 'arrow-up', keywords: ['upload'] },
    { name: 'at-sign', keywords: ['email', 'mention'] },
    { name: 'award', keywords: ['prize', 'medal'] },
    { name: 'bar-chart', keywords: ['analytics', 'stats'] },
    { name: 'battery', keywords: ['power', 'charge'] },
    { name: 'bell', keywords: ['notification', 'alert'] },
    { name: 'bluetooth', keywords: ['wireless'] },
    { name: 'bold', keywords: ['text', 'format'] },
    { name: 'book', keywords: ['read', 'library'] },
    { name: 'book-open', keywords: ['read', 'study'] },
    { name: 'bookmark', keywords: ['save', 'favorite'] },
    { name: 'box', keywords: ['package', 'container'] },
    { name: 'briefcase', keywords: ['work', 'business', 'job'] },
    { name: 'building', keywords: ['office', 'company'] },
    { name: 'bus', keywords: ['transport', 'travel'] },
    { name: 'cake', keywords: ['birthday', 'party'] },
    { name: 'calculator', keywords: ['math', 'compute'] },
    { name: 'calendar', keywords: ['date', 'schedule', 'event'] },
    { name: 'camera', keywords: ['photo', 'picture'] },
    { name: 'car', keywords: ['vehicle', 'transport'] },
    { name: 'check', keywords: ['done', 'complete', 'yes'] },
    { name: 'check-circle', keywords: ['done', 'success'] },
    { name: 'chevron-down', keywords: ['expand', 'arrow'] },
    { name: 'chevron-right', keywords: ['next', 'arrow'] },
    { name: 'circle', keywords: ['shape'] },
    { name: 'clock', keywords: ['time', 'schedule'] },
    { name: 'cloud', keywords: ['weather', 'storage'] },
    { name: 'code', keywords: ['programming', 'developer'] },
    { name: 'coffee', keywords: ['drink', 'cafe'] },
    { name: 'compass', keywords: ['navigation', 'direction'] },
    { name: 'copy', keywords: ['duplicate', 'clipboard'] },
    { name: 'credit-card', keywords: ['payment', 'money'] },
    { name: 'crop', keywords: ['image', 'edit'] },
    { name: 'database', keywords: ['storage', 'data'] },
    { name: 'dollar-sign', keywords: ['money', 'currency'] },
    { name: 'download', keywords: ['save', 'get'] },
    { name: 'droplet', keywords: ['water', 'liquid'] },
    { name: 'edit', keywords: ['pencil', 'write'] },
    { name: 'eye', keywords: ['view', 'see', 'watch'] },
    { name: 'eye-off', keywords: ['hide', 'invisible'] },
    { name: 'facebook', keywords: ['social', 'meta'] },
    { name: 'feather', keywords: ['light', 'write'] },
    { name: 'file', keywords: ['document', 'paper'] },
    { name: 'file-text', keywords: ['document', 'note'] },
    { name: 'film', keywords: ['movie', 'video'] },
    { name: 'filter', keywords: ['sort', 'funnel'] },
    { name: 'flag', keywords: ['country', 'mark'] },
    { name: 'flame', keywords: ['fire', 'hot'] },
    { name: 'flask-conical', keywords: ['science', 'chemistry'] },
    { name: 'folder', keywords: ['directory', 'files'] },
    { name: 'gamepad-2', keywords: ['game', 'play', 'controller'] },
    { name: 'gift', keywords: ['present', 'birthday'] },
    { name: 'git-branch', keywords: ['version', 'code'] },
    { name: 'github', keywords: ['code', 'repo'] },
    { name: 'globe', keywords: ['world', 'web', 'internet'] },
    { name: 'graduation-cap', keywords: ['education', 'school'] },
    { name: 'grid', keywords: ['layout', 'tiles'] },
    { name: 'hammer', keywords: ['tool', 'build'] },
    { name: 'hard-drive', keywords: ['storage', 'disk'] },
    { name: 'headphones', keywords: ['audio', 'music'] },
    { name: 'heart', keywords: ['love', 'like', 'favorite'] },
    { name: 'help-circle', keywords: ['question', 'info'] },
    { name: 'home', keywords: ['house', 'main'] },
    { name: 'image', keywords: ['photo', 'picture'] },
    { name: 'inbox', keywords: ['mail', 'messages'] },
    { name: 'info', keywords: ['help', 'about'] },
    { name: 'instagram', keywords: ['social', 'photo'] },
    { name: 'italic', keywords: ['text', 'format'] },
    { name: 'key', keywords: ['password', 'security'] },
    { name: 'lamp', keywords: ['light', 'idea'] },
    { name: 'laptop', keywords: ['computer', 'device'] },
    { name: 'layers', keywords: ['stack', 'design'] },
    { name: 'layout', keywords: ['design', 'grid'] },
    { name: 'leaf', keywords: ['nature', 'plant', 'eco'] },
    { name: 'library', keywords: ['books', 'read'] },
    { name: 'lightbulb', keywords: ['idea', 'bright'] },
    { name: 'link', keywords: ['chain', 'url'] },
    { name: 'linkedin', keywords: ['social', 'work'] },
    { name: 'list', keywords: ['bullet', 'items'] },
    { name: 'lock', keywords: ['security', 'private'] },
    { name: 'log-in', keywords: ['signin', 'enter'] },
    { name: 'log-out', keywords: ['signout', 'exit'] },
    { name: 'mail', keywords: ['email', 'message'] },
    { name: 'map', keywords: ['location', 'navigate'] },
    { name: 'map-pin', keywords: ['location', 'place'] },
    { name: 'maximize', keywords: ['fullscreen', 'expand'] },
    { name: 'megaphone', keywords: ['announce', 'speak'] },
    { name: 'menu', keywords: ['hamburger', 'nav'] },
    { name: 'message-circle', keywords: ['chat', 'comment'] },
    { name: 'message-square', keywords: ['chat', 'comment'] },
    { name: 'mic', keywords: ['audio', 'voice', 'record'] },
    { name: 'minimize', keywords: ['reduce', 'shrink'] },
    { name: 'minus', keywords: ['remove', 'subtract'] },
    { name: 'monitor', keywords: ['screen', 'display'] },
    { name: 'moon', keywords: ['night', 'dark'] },
    { name: 'more-horizontal', keywords: ['menu', 'dots'] },
    { name: 'mountain', keywords: ['nature', 'outdoor'] },
    { name: 'mouse', keywords: ['click', 'pointer'] },
    { name: 'move', keywords: ['drag', 'arrange'] },
    { name: 'music', keywords: ['audio', 'song'] },
    { name: 'navigation', keywords: ['gps', 'direction'] },
    { name: 'package', keywords: ['box', 'ship'] },
    { name: 'palette', keywords: ['color', 'art', 'design'] },
    { name: 'paperclip', keywords: ['attach', 'file'] },
    { name: 'pause', keywords: ['stop', 'wait'] },
    { name: 'pen-tool', keywords: ['draw', 'design'] },
    { name: 'percent', keywords: ['discount', 'math'] },
    { name: 'phone', keywords: ['call', 'mobile'] },
    { name: 'pie-chart', keywords: ['analytics', 'stats'] },
    { name: 'pin', keywords: ['location', 'mark'] },
    { name: 'plane', keywords: ['airplane', 'travel', 'flight'] },
    { name: 'play', keywords: ['start', 'video'] },
    { name: 'plug', keywords: ['power', 'electric'] },
    { name: 'plus', keywords: ['add', 'new', 'create'] },
    { name: 'pocket', keywords: ['save', 'later'] },
    { name: 'power', keywords: ['on', 'off', 'switch'] },
    { name: 'printer', keywords: ['print', 'paper'] },
    { name: 'puzzle', keywords: ['game', 'piece'] },
    { name: 'radio', keywords: ['audio', 'broadcast'] },
    { name: 'refresh-cw', keywords: ['reload', 'sync'] },
    { name: 'repeat', keywords: ['loop', 'again'] },
    { name: 'rocket', keywords: ['launch', 'space', 'fast'] },
    { name: 'rotate-cw', keywords: ['turn', 'spin'] },
    { name: 'rss', keywords: ['feed', 'subscribe'] },
    { name: 'ruler', keywords: ['measure', 'size'] },
    { name: 'save', keywords: ['disk', 'store'] },
    { name: 'scan', keywords: ['barcode', 'qr'] },
    { name: 'scissors', keywords: ['cut', 'trim'] },
    { name: 'search', keywords: ['find', 'look'] },
    { name: 'send', keywords: ['message', 'email'] },
    { name: 'server', keywords: ['computer', 'backend'] },
    { name: 'settings', keywords: ['gear', 'config'] },
    { name: 'share', keywords: ['social', 'send'] },
    { name: 'shield', keywords: ['security', 'protect'] },
    { name: 'shopping-bag', keywords: ['buy', 'store'] },
    { name: 'shopping-cart', keywords: ['buy', 'ecommerce'] },
    { name: 'shuffle', keywords: ['random', 'mix'] },
    { name: 'sidebar', keywords: ['panel', 'menu'] },
    { name: 'slack', keywords: ['chat', 'work'] },
    { name: 'smartphone', keywords: ['phone', 'mobile'] },
    { name: 'smile', keywords: ['happy', 'emoji'] },
    { name: 'speaker', keywords: ['audio', 'sound'] },
    { name: 'square', keywords: ['shape', 'box'] },
    { name: 'star', keywords: ['favorite', 'rating'] },
    { name: 'sun', keywords: ['light', 'day', 'bright'] },
    { name: 'table', keywords: ['grid', 'data'] },
    { name: 'tablet', keywords: ['device', 'ipad'] },
    { name: 'tag', keywords: ['label', 'category'] },
    { name: 'target', keywords: ['goal', 'aim'] },
    { name: 'terminal', keywords: ['code', 'command'] },
    { name: 'thermometer', keywords: ['temperature', 'weather'] },
    { name: 'thumbs-down', keywords: ['dislike', 'bad'] },
    { name: 'thumbs-up', keywords: ['like', 'good'] },
    { name: 'toggle-left', keywords: ['switch', 'off'] },
    { name: 'toggle-right', keywords: ['switch', 'on'] },
    { name: 'tool', keywords: ['wrench', 'fix'] },
    { name: 'trash', keywords: ['delete', 'remove'] },
    { name: 'trending-up', keywords: ['growth', 'increase'] },
    { name: 'trophy', keywords: ['winner', 'award'] },
    { name: 'truck', keywords: ['delivery', 'ship'] },
    { name: 'tv', keywords: ['screen', 'video'] },
    { name: 'twitter', keywords: ['social', 'x'] },
    { name: 'type', keywords: ['text', 'font'] },
    { name: 'umbrella', keywords: ['rain', 'weather'] },
    { name: 'underline', keywords: ['text', 'format'] },
    { name: 'unlock', keywords: ['open', 'security'] },
    { name: 'upload', keywords: ['send', 'file'] },
    { name: 'user', keywords: ['person', 'account'] },
    { name: 'users', keywords: ['people', 'team', 'group'] },
    { name: 'video', keywords: ['camera', 'record'] },
    { name: 'voicemail', keywords: ['audio', 'message'] },
    { name: 'volume-2', keywords: ['audio', 'sound'] },
    { name: 'wallet', keywords: ['money', 'payment'] },
    { name: 'watch', keywords: ['time', 'clock'] },
    { name: 'wifi', keywords: ['wireless', 'internet'] },
    { name: 'wind', keywords: ['weather', 'air'] },
    { name: 'x', keywords: ['close', 'cancel'] },
    { name: 'zap', keywords: ['lightning', 'fast', 'electric'] },
    { name: 'zoom-in', keywords: ['magnify', 'enlarge'] },
    { name: 'zoom-out', keywords: ['shrink', 'reduce'] },
];
